spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soap

    username: gatman
    password: gatman

  liquibase:
    change-log: db/changelog/db.changelog-master.yaml

server:
  port: 9000
